### ISSUE TITLE
Cannot add bots ingame?

### ISSUE THREAD

**Issue by Kreegoth** [jackpoz/BotFarm#11]
Maybe I am misunderstanding how far this is into development. But this program does actually add bots to game?

I have set up the configuration correctly. It loads np.
says its set up 30 accounts. (No new accounts are made in AUTH DB though...)
Stats shows 30 bots active 0 connected 0 ingame.

Any help would be appreciated.

**Comment by Kreegoth** [comment]
It seems for some reason having looked into this it is throwing unknown account errors and not actually creating the account....

It is creating the botinfos.xml but not placing info in actual database.

**Comment by tkrokli** [comment]
I haven't used it yet, but I seem to remember that you need to have a gmlevel 3 account set up for this. Maybe the account name needs to be inserted somewhere and you have forgotten to put it in the right file?

**Comment by jackpoz** [comment]
@Kreegoth the readme on homepage https://github.com/jackpoz/BotFarm says
>fill the Username and Password fields with an account with ".account create" permissions to allow the BotFarm to automatically create new accounts when required. Make sure this account has already a character.

**Comment by Kreegoth** [comment]
Ok i believe i figured this out. It was a permissions issue for sure.

Next question should bots show up in the Who list? How do i find them in game?

**Comment by jackpoz** [comment]
you can see them in the /who list , they are created as Human Priest so it's easy to spot them anyway
