### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by sesserg** [jackpoz/BotFarm#17]
After configuring and launching - clear black window.
WIN 7x64.
This for ready binaries and for binaries compiled by me.
Maybe add any logging.

**Comment by jackpoz** [comment]
The log is already there https://github.com/jackpoz/BotFarm/blob/master/BotFarm/BotFactory.cs#L42

**Comment by tkrokli** [comment]
Is there any "Logger" and "Appender" to be set in the XML config, like in the TrinityCore files?

**Comment by jackpoz** [comment]
https://github.com/jackpoz/BotFarm/blob/master/BotFarm/App.config is all you can configure

**Comment by tkrokli** [comment]
OK, thanks for confirming this.

**Comment by jackpoz** [comment]
Please try again using latest binaries (make sure to install VS2015 Redistributable first)

**Comment by sesserg** [comment]
All OK.
But Some questions:
Must do bots anything? They are spawn, and stay in one point and don't doing anything.
How can I customize Bot's Names?
It need change this tessings:?
                          <BotBehaviorSettings>
                            <Name>Default</Name>
                            <Probability>100</Probability>
                            <AutoAcceptGroupInvites>true</AutoAcceptGroupInvites>
                            <AutoAcceptResurrectRequests>true</AutoAcceptResurrectRequests>
                            <AutoResurrect>true</AutoResurrect>
                            <Begger>false</Begger>
                        </BotBehaviorSettings>

**Comment by jackpoz** [comment]
bots can be invited to party, can be teleported around, can autorez by walking to their corpse, can beg for money to other non-bot players. You can customize the bots behavior editing https://github.com/jackpoz/BotFarm/blob/master/BotFarm/BotGame.cs and implementing your own logic or keep an eye on https://github.com/jackpoz/BotFarm/commits/master to see which new features are added.

Bot names customization is already tracked at https://github.com/jackpoz/BotFarm/issues/6 , I was thinking about having a list of names that BotFarm can use.
