### ISSUE TITLE
TC rev. version?

### ISSUE THREAD

**Issue by gpcore** [jackpoz/BotFarm#21]
Hello, what tc core version support right now?

**Comment by jackpoz** [comment]
3.3.5

**Comment by gpcore** [comment]
Camon, update it to 6.2.2 : )))

**Comment by jackpoz** [comment]
TC 6.2.2 is too incomplete and it will require too much effort to update the packet structures/opcodes with every new WoW version. It's kinda out of scope of this project (someone could fork it and work on a 6.x port)
