### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by gpcore** [jackpoz/BotFarm#22]
Can you explain how compile this?

I am use VS 13 and got erros on compile like

The name 'DetourCLI' does not exist in the current context
The name 'VMapCLI' does not exist in the current context
The name 'MapCLI' does not exist in the current context

Could not resolve this reference. Could not locate the assembly "cli". Check to make sure the assembly exists on disk

Invalid expression term '.' AutomatedGame.cs	138	37	Client

**Comment by jackpoz** [comment]
for the "does not exist" errors read https://github.com/jackpoz/BotFarm/blob/master/README.md , in particular the part
>- make sure to read [README.md in BotFarm/lib folder](https://github.com/jackpoz/BotFarm/blob/master/BotFarm/lib/README.md) too with additional steps about required dependencies

As for Visual Studio 2013, keep an eye on https://github.com/jackpoz/BotFarm/commits/master , I changed the solution to VS 2015 2 days ago https://github.com/jackpoz/BotFarm/commit/5f5884ed0d00244a0f1943d7a221a6a8e5b14125 and started using C# 6.0 features that are supported only by VS2015

If you are using Windows x64 bits you could simple use the binaries available at https://ci.appveyor.com/project/jackpoz/botfarm/build/artifacts automatically updated at each new commit

**Comment by gpcore** [comment]
Thank you.
