### ISSUE TITLE
How to make the bots do stuff?

### ISSUE THREAD

**Issue by sout12** [jackpoz/BotFarm#24]
Is their a way to config the bot to do something and stuffz? And why is she naked ;o? 
![wowscrnshot_111715_224837](https://cloud.githubusercontent.com/assets/15899910/11232112/5cf04b3e-8d7d-11e5-868d-b37b9511737a.jpg)

**Comment by tkrokli** [comment]
The characters being undressed is a known issue, even used to be on Blizzard servers. It is part something about the cache reading, part a server opcode issue, if not more possible causes. It can sometimes be remedied by logging out and in again, sometimes by leaving the zone and come back.
(If you are interested in this specific issue, search https://github.com/TrinityCore/TrinityCore/issues for the keyword `naked`.)

I can't help you with the bot commands, I have just very recently got BotFarm to work for myself.

**Comment by jackpoz** [comment]
You can configure what bots can do at https://github.com/jackpoz/BotFarm/blob/master/BotFarm/App.config#L48 , it's a list of different behaviors that you can customize. 
You can define different behaviors and let BotFarm randomly choose how each bot will behave by using the Probability property.

I'd suggest to keep an eye on https://github.com/jackpoz/BotFarm/commits/master for new features as they get added. The current state of BotFarm is more for developers than for users.
