### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by jackpoz** [jackpoz/BotFarm#25]
Document what the bots can do and how to set up different bot behaviors. The homepage README feels like the best place for this kind of documentation for the time being.

**Comment by jackpoz** [comment]
Started at https://github.com/jackpoz/BotFarm/wiki

**Comment by tkrokli** [comment]
I approve of this.

![seal of approval](https://cloud.githubusercontent.com/assets/4903600/11314397/77b26eec-8fe5-11e5-8ee7-1cbee6a18a75.jpg)

**Comment by jackpoz** [comment]
Updated https://github.com/jackpoz/BotFarm/wiki with triggers documentation
