### ISSUE TITLE
Bots dont move?

### ISSUE THREAD

**Issue by massakre88** [jackpoz/BotFarm#26]
The bot join the game but stand in the same position. i made party with him but still dont move.. its normal?

**Comment by tkrokli** [comment]
Looks like you need to use some kind of command in /p (party/group) chat.
Unfortunately, I don't know what those commands are, so will have to wait for a simple manual.
You might as well try to use any form of talk in party chat to see what happens, as well as testing out different forms of prefixes to commands, like + (plus), . (dot) or / (slash). See what happens.

**Comment by jackpoz** [comment]
> Looks like you need to use some kind of command in /p (party/group) chat.

nope, there are no commands to write in /p .

**Comment by jackpoz** [comment]
@massakre88 you can check the list of current features at https://github.com/jackpoz/BotFarm/issues/17#issuecomment-154063072 for the moment , https://github.com/jackpoz/BotFarm/blob/master/BotFarm/App.config#L48 allows to define different behaviors for the bots. I'll write a few lines in the homepage readme about current bots features.

**Comment by jackpoz** [comment]
https://github.com/jackpoz/BotFarm/wiki is going to store the documentation about BotFarm
