### ISSUE TITLE
Allow bots to follow party leaders

### ISSUE THREAD

**Issue by jackpoz** [jackpoz/BotFarm#27]
Add a config option to specify if bots should follow party leaders. Take into account other actions like Resurrecting, maybe add a priority.

**Comment by tkrokli** [comment]
:+1: Nice. I think it will be one of the most popular options.

**Comment by jackpoz** [comment]
https://github.com/jackpoz/BotFarm/commit/6b1342accabc4b6742a24d9d19e6da892ba22f4c

**Comment by madmax765** [comment]
Nice
