### ISSUE TITLE
runtime "error" (not a crash)

### ISSUE THREAD

**Issue by Aokromes** [jackpoz/BotFarm#3]
aok2 - Object reference not set to an instance of an object.    at Client.
World.Network.WorldSocket.BeginRead(AsyncCallback callback, Object state) in c:\SimpleWoW\Client\World\Network\WorldSocket.cs:line 192
at Client.World.Network.WorldSocket.Start() in c:\SimpleWoW\Client\World\Network\WorldSocket.cs:line 411
at Client.World.Network.WorldSocket.ReadPayloadCallback(IAsyncResult result)
in c:\SimpleWoW\Client\World\Network\WorldSocket.cs:line 357

 i think it triggered when it tried to login with one account without chars

**Comment by jackpoz** [comment]
fixed in https://github.com/jackpoz/BotFarm/commit/49deb02fa6f78137c5db986e5e0e47bac35bb682
