### ISSUE TITLE
no *.config 

### ISSUE THREAD

**Issue by Keldo** [jackpoz/BotFarm#39]
By either downloading the Archived Zip from Appveyor or Building with Visual Studio 2015, no *.config is found or generated

**Comment by jackpoz** [comment]
Clicking on the homepage link https://ci.appveyor.com/project/jackpoz/botfarm and then Artifacts downloads a zip archive with the config file, as displayed in the screenshot below.

![botfarm config](https://cloud.githubusercontent.com/assets/1153754/20174441/11658da6-a73e-11e6-902e-01e512ae9e1e.png)
