### ISSUE TITLE
local server only?

### ISSUE THREAD

**Issue by Keldo** [jackpoz/BotFarm#40]
Was testing this on a remote 7.1.0 (Legion) server, seems like it doesnt connect, I dont have a 3.3.5a server to test with.

Port set to 1119, set username to bnet email address, password, copied maps, vmaps, dbc to same directory though I dont see why they are needed if this is just intended to connect and randomly create

**Comment by jackpoz** [comment]
it doesn't support 7.1.0, it supports only 3.3.5a.
Maps, Vmaps and MMaps are needed for pathfinding. DBCs are currently needed for Explore achievements.
