### ISSUE TITLE
Extra Allocation in CharacterEnumeration.cs

### ISSUE THREAD

**Issue by HelloKitty** [jackpoz/BotFarm#41]
You initialize the display item array in the selection character character structure with a length of 20 but WoW only sends 19 display items for the character at the selection screen. Works fine, since read Length - 1 items but it definitely caused me an issue since I sometimes use your bot as a reference. I had to peak into Trinitycore to see why it wasn't working when reading 20 items for my own libraries.

**Comment by jackpoz** [comment]
got a line ?

**Comment by HelloKitty** [comment]
@jackpoz Yea that line, it's not too important but it definitely confused me for a tiny bit as to why only 19 character screen display items were coming down on my end lol.
