### ISSUE TITLE
Failed to connect (ToBigInteger)

### ISSUE THREAD

**Issue by Zyres** [jackpoz/BotFarm#44]
Hi

maybe it is my fault, can you give me advice what I've done wrong?

![error](http://i.imgur.com/mpNdDJv.png)

The worldserver sends the following:
[SERVER]: sent SMSG_AUTH_CHALLENGE (0x1EC) of 24 bytes.

**Comment by jackpoz** [comment]
Could you provide some info about what server are you connecting to ? it's probably easier if you debug BotFarm and see how it's failing the authentication to worldserver

**Comment by jackpoz** [comment]
According to https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Server/WorldSocket.cpp#L139 SMSG_AUTH_CHALLENGE is supposed to be 37 bytes, not 24.

**Comment by Zyres** [comment]
I tried it on AscEmu. Maybe we send a incomplete packet there, but currently it seems to work fine for WotLK and Cataclysm clients.

**Comment by jackpoz** [comment]
I have no clue what AscEmu is doing at https://github.com/AscEmu/AscEmu/blob/3bd8889b3f91656236a7853bd6d4af4f837947db/src/world/Server/WorldSocket.cpp#L281 but it looks weird. I doubt it's an issue related to BotFarm

**Comment by jackpoz** [comment]
Actually now that I take a closer look I can clearly see a familiar name at https://github.com/AscEmu/AscEmu/blob/3bd8889b3f91656236a7853bd6d4af4f837947db/src/world/Server/WorldSocket.cpp#L283 , which was added in https://github.com/arcemu/arcemu/commit/4a51100757fb172f9f15af98db5d4a08e83494b0#diff-70cbb7f2434c3bb6dd31c8d48399c130R250
