### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Pursche** [jackpoz/BotFarm#51]
Hi Jackpoz!

This looks a bit like what we have started working on over here: https://github.com/novuscore/NovusCore-Client

You mentioned in a comment that this could be useful, but it is GPL licensed and thus not compatible with our MIT license.

Would you be willing to let us use parts of this repository under an MIT license? You will of course get credits if we use anything and I can assure you that I will never take the NovusCore Client private.

**Comment by jackpoz** [comment]
Hey @Pursche, sure, feel free to use the sources of this project in yours with the MIT license :)
