### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by jackpoz** [jackpoz/BotFarm#53]
.NET Core 3.1 added support to C++/CLI on Windows, allowing (on paper at least) to migrate BotFarm to .NET Core

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/

**Comment by illfated** [comment]
Thanks, I have not read up on that development lately, but will look into it more now.

**Comment by jackpoz** [comment]
https://github.com/jackpoz/TrinityCore/commit/27c1b467d2f7c97818b3a7f2a23addfa603126c9

https://github.com/jackpoz/BotFarm/commit/1f9acf36ed2c7ec5b6167fde522af8df95cf3970
https://github.com/jackpoz/BotFarm/commit/be02bfa156d9af9f6ba068d5c29b63f92432f5cf
https://github.com/jackpoz/BotFarm/commit/fbeea9ec70f00c6a8465e85af93f2443a6a01dc8
https://github.com/jackpoz/BotFarm/commit/2b02b27ce1f5fffb3a4654f081d7b69f74049a2c

Just need to update appveyor now

**Comment by jackpoz** [comment]
AppVeyor updated CMake to 3.17.1 and after fiddling with the build it's working good
