### ISSUE TITLE
After bot creation no logon

### ISSUE THREAD

**Issue by Wizards2k** [jackpoz/BotFarm#54]
![image](https://user-images.githubusercontent.com/35931808/78797600-30ecf380-79b8-11ea-8beb-864ad9b9250a.png)

the bot stuck in logon_challege state

**Comment by jackpoz** [comment]
you can see "Unknown account name" in the console. 
Check if the account was actually created. If not, check if the botfarm account has access to ".account create" ingame GM command.

**Comment by Wizards2k** [comment]
yes the account is admin account, i see also in world console, account create command... 
![image](https://user-images.githubusercontent.com/35931808/78800319-99899f80-79bb-11ea-84dc-24f53c17354d.png)

my wow server version, is the trinitycore branch335 with trickery bot... dont' knwo if compatible with botfarm

**Comment by jackpoz** [comment]
is that account in the database ? can you login using that username and password ?

**Comment by Wizards2k** [comment]
no, i think the problem is the REALMID, my server have 1, if i set 1 in realm account botfarm say that:

![image](https://user-images.githubusercontent.com/35931808/78800911-50861b00-79bc-11ea-9234-0775eae91d2b.png)

if i try with -1, another error.... if i try with 0, seems work.. but with the false creation...

**Comment by jackpoz** [comment]
Log with World of Warcraft client with the botfarm account, try ".account create" and then try logging with those credentials.

The RealmID is a 0 based index on the list of realms returned, it's not the Realm ID stored in the database (since the client has no clue about that)

**Comment by Wizards2k** [comment]
not logon... in the account table the is not BOT1715782421 account... so don't know why...

**Comment by jackpoz** [comment]
most likely because the "admin" BotFarm doesn't have access to ".account create" .
You probably need to assign the RBAC permission  in the database, you can ask the TrinityCore guys how to do that (forum or irc or discord).

**Comment by Wizards2k** [comment]
maybe right, i have tryed .account create ingame.. and not work..... only from console command

**Comment by Wizards2k** [comment]
ok, i have update rbac tables, now the account is created.. but BOT STILL in login attempt... i tryed to login with bot account .. and login success... but no pg are created in account at moment.....

**Comment by Wizards2k** [comment]
i have populated rbac tables and now login with bot... ok ..
